apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio04kubenews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: desafio04kubenews
  template:
    metadata:
      labels:
        app: desafio04kubenews
    spec:
      containers:
        - name: desafio04kubenews
          image: viniciuscaol/desafio04:latest
          ports:
            - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#123"
          - name: DB_HOST
            value: "postgre"