apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio04kubenews
spec:
  replicas: 10
  selector:
    matchLabels:
      app: desafio04kubenews
  template:
    metadata:
      labels:
        app: desafio04kubenews
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/prot: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: desafio04kubenews
          image: viniciuscaol/desafio04:v1.2.{{TAG}}
          ports:
            - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#123"
          - name: DB_HOST
            value: "postgre"